sudo: required
services:
  - docker


before_install:
  - docker build -t vndlovu/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true vndlovu/docker-react npm run test -- --coverage


deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-eu-west-1-009168092773"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
  skip_cleanup: true

